version: '3.9'

services:
    postgres:
        container_name: ${STACK_NAME:-nest}-pgsql
        image: postgres
        environment:
            POSTGRES_DB: ${DATABASE_NAME:-nest_db}
            POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-P@s5word}
            PGDATA: /data/postgres
            TZ: ${TIMEZONE:-America/New_York}
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        # ports:
        #     - '5432:5432'
        restart: unless-stopped

    pgadmin:
        container_name: ${STACK_NAME:-nest}-pgadmin
        image: dpage/pgadmin4
        depends_on:
            - postgres
            - redis
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-your-email@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-P@s5word}
            PGADMIN_CONFIG_SERVER_MODE: 'True'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ${DATA_FOLDER}/pgadmin/servers.json:/pgadmin4/servers.json
        ports:
            - '5433:80'
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: ${STACK_NAME:-nest}-redis
        # ports:
        #     - 6379:6379
        volumes:
            - redis-data:/data
        restart: unless-stopped

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        image: ${STACK_NAME:-nest}
        container_name: ${STACK_NAME:-nest}-app
        ports:
            - ${PORT:-4000}:4000
        volumes:
            - app-data:/home/node/app
            - ./.env.docker:/home/node/app/.env
            - ./firebase.spec.json:/home/node/app/firebase.spec.json
        depends_on:
            - postgres
            - redis
        restart: unless-stopped

volumes:
    postgresql-data:
        driver: local
    redis-data:
        driver: local
    pgadmin-data:
        driver: local
    app-data:
        driver: local
